# Generated by Django 4.2.6 on 2023-10-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Nifty50', max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='template_data/')),
            ],
        ),
    ]
