# Generated by Django 4.2.6 on 2023-10-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_serviceendpoints_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceendpoints',
            name='method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')]),
        ),
    ]
