# Generated by Django 4.2.6 on 2023-11-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_url', models.URLField(blank=True, max_length=255)),
                ('seller_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
